### ISSUE TITLE
feature request: jre and gstreamer packaged in the libreoffice appimage

### ISSUE THREAD

**Issue by Lvaskz** [antoniofaccioli/libreoffice-appimage#10]
Greetings, The appimages should be packages in which it should not be necessary to download some extra dependency (for libreoffice appimage, it needs gstreamer and jre) but for first-time users this is something that they may not be able to do until they have some experience with the software center or synaptic, so I request that you pack gstreamer and jre with libreoffice in the appimage. Libreoffice snap has this type of solution.

**Comment by probonopd** [comment]
> (for libreoffice appimage, it needs gstreamer and jre) 

LibreOffice can run without those. Having those merely adds functionality, but they are not strictly needed.

**Comment by Lvaskz** [comment]
Of course, the freeoffice appimage works perfectly well without them, however when I need to perform operations that need to gstremer and jre, it asks me to install the dependencies. For my part, this is not a problem if I can locate the dependencies in synaptic or if I have basic knowledge about adding ppas and other annoyances. But for a beginner user, performing this step becomes terribly frustrating.
Personally I consider that the appimages, flatpaks and snaps should not request more dependencies, but have everything necessary to operate at 100%. For some people requesting this is not necessary, but it is better to consider the end user and beginners, who have no idea how to do it. Sure, they can search the internet but this makes them less attractive and they will consider another option, let's say, "more complete". As I mentioned, it is not that the appimages that still need certain dependencies, are not functional but, I have run into a couple of cases in which looking for certain dependencies becomes a nightmare, this because, I do not find them or there are millions of similar versions and do not know what to install.
