### ISSUE TITLE
appimagetool cannot find the source

### ISSUE THREAD

**Issue by lobaluna** [antoniofaccioli/libreoffice-appimage#17]
Please help. Dont know how to verbalize this issue:

This is the output of the command (Lubuntu 19.10) in terminal (last lines, only):
(the script make_libreoffice_appimage is located in ~/bin folder in my /home directory:

`
    HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

    + chmod a+x ./appimagetool
    + set +x
    appimagetool, continuous build (commit 64321b7), build 2111 built on 2019-11-23 22:20:53 UTC
    Desktop file not found, aborting
    + [[ N == \Y ]]
    + mkdir -p ../out/
    + mv '*.AppImage*' ../out/
    mv: cannot stat '*.AppImage*': No such file or directory
`

I tried to run the last commands one by one, but I get stuck here:
(the script make_libreoffice_appimage is located in ~/bin folder in my /home directory:

`~/bin/LibreOffice$ VERSION=6.2.8 ./appimagetool -v ./LibreOffice.AppDir/
appimagetool, continuous build (commit 64321b7), build 2111 built on 2019-11-23 22:20:53 UTC
Desktop file not found, aborting
`

**Comment by probonopd** [comment]
Where in `./LibreOffice.AppDir/` is your desktop file?

**Comment by lobaluna** [comment]
There is no Desktop file.El 8 feb. 2020 3:14 a. m., probonopd <notifications@github.com> escribió:Where in ./LibreOffice.AppDir/ is your desktop file?

**Comment by 3563deb6753** [comment]
Hi I had the same problem and fixed the script so that it works for me at least  pull request #23.

**Comment by lobaluna** [comment]
> Hi I had the same problem and fixed the script so that it works for me at least pull request #23.

Thank you! I'll give it a try :)
