### ISSUE TITLE
AppImage links on https://www.libreoffice.org/download/appimage/ broken

### ISSUE THREAD

**Issue by probonopd** [antoniofaccioli/libreoffice-appimage#22]
On https://www.libreoffice.org/download/appimage/
the links are broken, e.g.,:

* https://libreoffice.soluzioniopen.com/stable/fresh/LibreOffice-fresh.basic-x86_64.AppImage
* https://libreoffice.soluzioniopen.com/stable/still/LibreOffice-still.basic-x86_64.AppImage

> The requested URL was not found on this server.

**Comment by antoniofaccioli** [comment]
Fixed, thanks for reporting.
