### ISSUE TITLE
Is it usefull to include fonts in an AppImage?

### ISSUE THREAD

**Issue by db-inf** [antoniofaccioli/libreoffice-appimage#25]
The current scripts includes ~70MB of fonts into the AppImage. Because an AppImage is a closed container, that is mounted to unpredictable mountpoints, these fonts are not available outside the running AppImage. Is it not better to have only the system installed fonts available in your Office applications?

In my fork I have now a branch that has one extra line `find ./opt/libreoffice*/share/fonts -depth -mindepth 1 -delete`, to remove these fonts. The resulting AppImage runs fine (and is some MB smaller).

**Comment by antoniofaccioli** [comment]
Ok, right. I check if those fonts are installed by the appimage tool or if they are distributed by default with libreoffice.

**Comment by db-inf** [comment]
These fonts are, from the `libobasis6.4-ooofonts_6.4.7.2-2_amd64.deb` in `LibreOffice_6.4.7_Linux_x86-64_deb.tar.gz`

**Comment by antoniofaccioli** [comment]
Yes I saw, I have to check if these fonts are also included in the package for Windows. In principle, the appimage packages that are created must contain all the files normally distributed by TDF.
