### ISSUE TITLE
Unresolved symbolic links prevent easy desktop integration

### ISSUE THREAD

**Issue by db-inf** [antoniofaccioli/libreoffice-appimage#26]
The current distribution contains symbolic links to absolute paths `/opt/libreoffice...` from the appdir's `./usr/local/bin` for the application's executable, and from it's `./usr/share/applications` for the _.desktop_ files.

When installing or unpacking the distribution to `/opt`, this may make sense, but when packaged into an AppImage, these links are broken. Therefor I think that this should only be remedied for the AppImage.

In the AppImage, these links have no use, even if they were fixed by making them relative. If however they were replaced by the real _.desktop_ files they are meant to link to, it would become easy to integrate the AppImage into the user's desktop. All that would be required, would be :
- For all users: 
  - copy the AppImage's `./usr/share` directory over to `/usr/local/share`
  - symlink to the AppImage file in `/usr/local/bin`, under the name of the application's executable, as used in the `Exec=` clause of the _.desktop_ files. Example :
    `sudo ln -s /opt/appimages/LibreOffice-6.4.7.it.help-x86_64.AppImage /usr/local/bin/libreoffice6.4`
  - Update the MIME database:
	`sudo update-mime-database /usr/local/share/mime`
  - Update the application database:
    `sudo update-desktop-database /usr/local/share/applications`
- For a single user: use the user's `~/bin` and `~/.local/share` for the same purpose, and ...
  - Update the personal MIME database:
	`update-mime-database ~/.local/share/mime`
  - Update the personal application database:
    `update-desktop-database ~/.local/share/applications`
- And of course an instruction to explain this procedure.

**Comment by antoniofaccioli** [comment]
Interesting solution, we haven't actually solved this so far because the appimage packages are meant to be portable versions.
I take this into account for non-portable packages.

**Comment by db-inf** [comment]
I just want to make 2 remarks.

1. Fixing this does not make the LibreOffice AppImage less portable. It just makes it easier to integrate it into whichever desktop it is ported to.
1. The [AppImage documentation](https://docs.appimage.org/reference/desktop-integration.html) itself devotes attention to desktop integration

**Comment by antoniofaccioli** [comment]
ok
