### ISSUE TITLE
QUESTION: Download appimage from libreoffice.org or use this script?

### ISSUE THREAD

**Issue by Moltkex** [antoniofaccioli/libreoffice-appimage#27]
Hi, 
I'm currently using **LibreOffice-fresh.standard-x86_64.appimage** which I downloaded from here https://www.libreoffice.org/download/appimage/ on Debian 10, however, there's this issue that I can't use Spanish spellchecker but English only in calc, I can in writer though. Also, spellchecking works fine if LO is installed  via apt, so I  was wondering, given this script will build the appimage using the .debs from Debian repos, whether it'll make any difference? I guess trying is the only way to find out but thought of asking anyway hoping someone might have some experience/knowledge regarding this. In short, Is there any difference between the appimage built by this script from the one I'm using? Thanks.

**Comment by Moltkex** [comment]
Ok, just tried the script and got this: 
<code>appimagetool, continuous build (commit 0880085), build 2133 built on 2020-07-09 12:25:52 UTC
WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
Desktop file not found, aborting
+ [[ N == \Y ]]
+ mkdir -p ../out/
+ mv '*.AppImage*' ../out/
mv: no se puede efectuar `stat' sobre '*.AppImage*': No existe el fichero o el directorio
</code>
so it didn't work. I tried using this <code>./make_libreoffice_appimage fresh x86-64 es N Y N N</code> is it ok?

**Comment by antoniofaccioli** [comment]
Hi,
have you tried the packages in Spanish downloadable from here https://libreoffice.soluzioniopen.com/stable-2/?
The libreoffice.org site still downloads the packages from my site.

**Comment by Moltkex** [comment]
> Hi,
> have you tried the packages in Spanish downloadable from here https://libreoffice.soluzioniopen.com/stable-2/?
> The libreoffice.org site still downloads the packages from my site.

Hi, 
No, I haven't. Are these different from the ones on libreoffice.org? I downloaded the Spanish from there and everything works fine except for the spellchecking in calc. I even installed the dictionaries but no luck. I tried the full version too, same thing; if want to use/change spellchecking from English to Spanish or (I just checked) any other language in calc, it won't work, unless I'm missing something, my understanding is: I choose Spanish or something else from the drop-down menu and it should stick so it spellchecks the whole sheet in that lang, am I wrong? Is it normal that it reverts back to English for the next word? I don't think it is since LO installed via apt/.deb doesn't. I tried fresh-standard and full. Versions 6.4.3.2 and 7.0.1. I think this is more like a bug. Will try yours anyway and see if that one works. Thanks for your reply.

**Comment by Moltkex** [comment]
I downloaded and tried LibreOffice-fresh.standard-x86_64.AppImage from your site, same thing. I even unchecked English, both US and GB from the options to see if it makes any difference but it didn't. Looks like a bug, behaves like a bug, think's a bug in the appimage. Guess I'll have to deal with it and do the spellchecking by hand as I type, not ideal but ... Thanks for your time.
