### ISSUE TITLE
Include version name in the name of appimage generated

### ISSUE THREAD

**Issue by stragu** [antoniofaccioli/libreoffice-appimage#29]
Hi there! Not sure if the issue is something that can be fixed here, but here goes:

Currently, the download from the [LO AppImage page](https://www.libreoffice.org/download/appimage/) links a file that has the target architecture and the "Fresh" or "Still" information in the filename. However, it does not have the precise version number (e.g. 7.1.4), which makes it difficult to know if the appimage is built from the latest release or not.

I download it again the other day after the announcement of 7.1.4 but ended up with 7.1.3, the version I already had. Including the precise version name would save users and the LO servers quite a few unnecessary downloads.

**Comment by antoniofaccioli** [comment]
I'm arranging the releases, it should be alright today.
As for the release numbers, it is not possible to enter them as the appimage update system would no longer be usable.
Versions with the number will be available on libreoffice.soluzioniopen.com

**Comment by stragu** [comment]
I only learned about https://libreoffice.soluzioniopen.com/ right after posting this issue! Thanks for the quick reply. That page is enough to identify the versions, so closing this now.
Cheers! :slightly_smiling_face:
