### ISSUE TITLE
Cannot find .desktop file

### ISSUE THREAD

**Issue by chimak111** [antoniofaccioli/libreoffice-appimage#37]
This is different than https://github.com/antoniofaccioli/libreoffice-appimage/issues/28

Although I get a similar error in the end, I'm using Xubuntu 22.04. OP was on Arch.
```
+ chmod a+x ./appimagetool
+ set +x
appimagetool, continuous build (commit 4bcfe23), build <local dev build> built on 2022-08-17 01:03:50 UTC
Desktop file not found, aborting
+ [[ N == \Y ]]
+ mkdir -p ../out/
+ mv '*.AppImage*' ../out/
mv: cannot stat '*.AppImage*': No such file or directory
••• ~/Public/libre $ 
```

The full output is here: http://sprunge.us/p9HsSy

I wonder if the internal `//` in the paths below are causing the problem.
```
+ path=https://download.documentfoundation.org/libreoffice/stable//deb/x86_64/
+ package=LibreOffice__Linux_x86-64_deb.tar.gz
+ LibODownloadLink=https://download.documentfoundation.org/libreoffice/stable//deb/x86_64/LibreOffice__Linux_x86-64_deb.tar.gz
+ [[ N != \N ]]
+ [[ N != \N ]]
+ VERSION=
+ mkdir -p ./LibreOffice/LibreOffice.AppDir
+ cd ./LibreOffice
+ wget -c https://download.documentfoundation.org/libreoffice/stable//deb/x86_64/LibreOffice__Linux_x86-64_deb.tar.gz
--2022-08-27 08:43:08--  https://download.documentfoundation.org/libreoffice/stable//deb/x86_64/LibreOffice__Linux_x86-64_deb.tar.gz
```

Thank you for reading.

**Comment by reinob** [comment]
The problem is that the script fails to fetch the version number, because something changed at libreoffice.org.

You have to replace curl "https://www.libreoffice.org/download/download" with "curl "https://www.libreoffice.org/download/download-libreoffice" (2x), or replace "curl" with "curl -L" to follow redirections.

I think there's a pull request precisely fixing that, but it's not been merged yet.

**Comment by chimak111** [comment]
> The problem is that the script fails to fetch the version number, because something changed at libreoffice.org.
> 
> You have to replace curl "https://www.libreoffice.org/download/download" with "curl "https://www.libreoffice.org/download/download-libreoffice" (2x) ...

Thanks, your instructions worked perfectly!
