### ISSUE TITLE
"metadata missing" (warning) and "not found" (error; langpack de)

### ISSUE THREAD

**Issue by KurtPfeifle** [antoniofaccioli/libreoffice-appimage#4]
I used this script to build an AppImage with the following command line arguments:

     libreoffice-appimage daily x86-64 de Y N N

When building the beautifully working AppImage, I noticed a few glitches.

## 1. Warning: "metadata missing"
<pre>
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/startcenter.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information.
</pre>

## 2. Error: "Not Found"
<pre>
+libreoffice_appimage:147:main: [[ de != \N ]]
+libreoffice_appimage:148:main: [[ de == *\s\t\a\n\d\a\r\d* ]]
+libreoffice_appimage:154:main: [[ de == *\f\u\l\l* ]]
+libreoffice_appimage:161:main: [[ daily == \3\.* ]]
+libreoffice_appimage:165:main: langPackage=LibreOffice_6.0.0.0.alpha1_2017-11-08_Linux_x86-64_deb_langpack_de.tar.gz
+libreoffice_appimage:166:main: wget -c http://dev-builds.libreoffice.org/daily/master/Linux-rpm_deb-x86_64@70-TDF/current/LibreOffice_6.0.0.0.alpha1_2017-11-08_Linux_x86-64_deb_langpack_de.tar.gz
--2017-11-10 15:06:48--  http://dev-builds.libreoffice.org/daily/master/Linux-rpm_deb-x86_64@70-TDF/current/LibreOffice_6.0.0.0.alpha1_2017-11-08_Linux_x86-64_deb_langpack_de.tar.gz
Resolving dev-builds.libreoffice.org (dev-builds.libreoffice.org)... 89.238.68.201, 2a00:1828:a012:201::1
Connecting to dev-builds.libreoffice.org (dev-builds.libreoffice.org)|89.238.68.201|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-10 15:06:49 ERROR 404: Not Found.

+libreoffice_appimage:171:main: [[ Y == *\Y* ]]
+libreoffice_appimage:172:main: [[ de == *\s\t\a\n\d\a\r\d* ]]
+libreoffice_appimage:178:main: [[ de == *\f\u\l\l* ]]
+libreoffice_appimage:185:main: [[ daily == \3\.* ]]
+libreoffice_appimage:194:main: [[ de != \N ]]
+libreoffice_appimage:195:main: helpPackage=LibreOffice_6.0.0.0.alpha1_2017-11-08_Linux_x86-64_deb_helppack_de.tar.gz
+libreoffice_appimage:196:main: wget -c http://dev-builds.libreoffice.org/daily/master/Linux-rpm_deb-x86_64@70-TDF/current/LibreOffice_6.0.0.0.alpha1_2017-11-08_Linux_x86-64_deb_helppack_de.tar.gz
--2017-11-10 15:06:49--  http://dev-builds.libreoffice.org/daily/master/Linux-rpm_deb-x86_64@70-TDF/current/LibreOffice_6.0.0.0.alpha1_2017-11-08_Linux_x86-64_deb_helppack_de.tar.gz
Resolving dev-builds.libreoffice.org (dev-builds.libreoffice.org)... 89.238.68.201, 2a00:1828:a012:201::1
Connecting to dev-builds.libreoffice.org (dev-builds.libreoffice.org)|89.238.68.201|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-10 15:06:49 ERROR 404: Not Found.
</pre>

**Comment by probonopd** [comment]
Thanks @KurtPfeifle, the point about AppStream is also mentioned in https://github.com/AppImage/AppImageKit/wiki/Bundling-LibreOffice.

**Comment by antoniofaccioli** [comment]
Thanks @KurtPfeifle at this time the script does not support language packs for the daily version, but only for standard, full, fresh, and still.
I can add the option.
